[build]
  publish = "build"
  command = "npm run build"

# netlify.app â†’ custom domain 
[[redirects]]
  from = "/*"
  to = "https://erkanturgut.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["erkanturgut.netlify.app"] }

# sitemap
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# SPA fallback (EN ALTA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
